import type { ReportToolSettingsRegistry } from './reportSettingTypes';

export const reportSettingDefaults: ReportToolSettingsRegistry = {
  text: {
    toolType: 'text',
    general: [
      { key: 'text', label: 'Text', type: 'textarea', defaultValue: '{{report.name}}', description: 'ข้อความแสดงผล พร้อม support variables' },
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Text' },
    ],
    style: [
      { key: 'fontFamily', label: 'Font family', type: 'text', defaultValue: 'Inter' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 14, min: 8, max: 72, step: 1 },
      { key: 'fontWeight', label: 'Font weight', type: 'select', defaultValue: '400', options: [
        { label: 'Normal', value: '400' },
        { label: 'Bold', value: '700' },
      ] },
      { key: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
      { key: 'background', label: 'Background color', type: 'color', defaultValue: 'transparent' },
      { key: 'align', label: 'Align', type: 'select', defaultValue: 'left', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ] },
      { key: 'verticalAlign', label: 'Vertical align', type: 'select', defaultValue: 'top', options: [
        { label: 'Top', value: 'top' },
        { label: 'Middle', value: 'middle' },
        { label: 'Bottom', value: 'bottom' },
      ] },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 1.4, min: 1, max: 3, step: 0.1 },
      { key: 'letterSpacing', label: 'Letter spacing', type: 'number', defaultValue: 0, min: -2, max: 10, step: 0.5 },
      { key: 'padding', label: 'Padding', type: 'number', defaultValue: 4, min: 0, max: 64, step: 1 },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#94a3b8' },
      { key: 'borderWidth', label: 'Border width', type: 'number', defaultValue: 0, min: 0, max: 12, step: 1 },
      { key: 'borderStyle', label: 'Border style', type: 'select', defaultValue: 'solid', options: [
        { label: 'Solid', value: 'solid' },
        { label: 'Dashed', value: 'dashed' },
        { label: 'Dotted', value: 'dotted' },
      ] },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 0, min: 0, max: 48, step: 1 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 1, min: 0, max: 1, step: 0.05 },
      { key: 'autoFit', label: 'Auto fit text', type: 'boolean', defaultValue: true },
      { key: 'wrapText', label: 'Wrap text', type: 'boolean', defaultValue: true },
      { key: 'maxLines', label: 'Max lines', type: 'number', defaultValue: 0, min: 0, max: 20, step: 1 },
      { key: 'textOverflow', label: 'Text overflow', type: 'select', defaultValue: 'clip', options: [
        { label: 'Clip', value: 'clip' },
        { label: 'Ellipsis', value: 'ellipsis' },
        { label: 'Shrink', value: 'shrink' },
      ] },
    ],
    behavior: [
      { key: 'emptyDataMode', label: 'No data mode', type: 'select', defaultValue: 'show blank', options: [
        { label: 'Show blank', value: 'show blank' },
        { label: 'Show zero', value: 'show zero' },
        { label: 'Show No Data', value: 'show no data' },
        { label: 'Hide object', value: 'hide object' },
      ] },
    ],
    advanced: [
      { key: 'debugId', label: 'Debug ID', type: 'text' },
      { key: 'customClassName', label: 'Custom class name', type: 'text' },
    ],
  },
  image: {
    toolType: 'image',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Image' },
      { key: 'altText', label: 'Alt text', type: 'text', defaultValue: '' },
    ],
    data: [
      { key: 'imageUrl', label: 'Image source', type: 'text', defaultValue: '' },
      { key: 'imageSource', label: 'Source type', type: 'select', defaultValue: 'url', options: [
        { label: 'URL', value: 'url' },
        { label: 'Local path', value: 'local' },
        { label: 'Base64', value: 'base64' },
      ] },
    ],
    style: [
      { key: 'fitMode', label: 'Fit mode', type: 'select', defaultValue: 'contain', options: [
        { label: 'Contain', value: 'contain' },
        { label: 'Cover', value: 'cover' },
        { label: 'Fill', value: 'fill' },
        { label: 'Stretch', value: 'stretch' },
      ] },
      { key: 'lockAspectRatio', label: 'Lock aspect ratio', type: 'boolean', defaultValue: true },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 1, min: 0, max: 1, step: 0.05 },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 0, min: 0, max: 48, step: 1 },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#94a3b8' },
      { key: 'borderWidth', label: 'Border width', type: 'number', defaultValue: 0, min: 0, max: 12, step: 1 },
      { key: 'cropPosition', label: 'Crop position', type: 'select', defaultValue: 'center', options: [
        { label: 'Center', value: 'center' },
        { label: 'Top', value: 'top' },
        { label: 'Bottom', value: 'bottom' },
        { label: 'Left', value: 'left' },
        { label: 'Right', value: 'right' },
      ] },
    ],
    behavior: [
      { key: 'repeatOnPage', label: 'Repeat on page', type: 'boolean', defaultValue: false },
    ],
    advanced: [
      { key: 'debugId', label: 'Debug ID', type: 'text' },
    ],
  },
  line: {
    toolType: 'line',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Line' },
    ],
    style: [
      { key: 'strokeColor', label: 'Stroke color', type: 'color', defaultValue: '#111827' },
      { key: 'strokeWidth', label: 'Stroke width', type: 'number', defaultValue: 1, min: 1, max: 24, step: 1 },
      { key: 'strokeStyle', label: 'Stroke style', type: 'select', defaultValue: 'solid', options: [
        { label: 'Solid', value: 'solid' },
        { label: 'Dashed', value: 'dashed' },
        { label: 'Dotted', value: 'dotted' },
      ] },
      { key: 'startArrow', label: 'Start arrow', type: 'boolean', defaultValue: false },
      { key: 'endArrow', label: 'End arrow', type: 'boolean', defaultValue: false },
      { key: 'lineCap', label: 'Line cap', type: 'select', defaultValue: 'butt', options: [
        { label: 'Butt', value: 'butt' },
        { label: 'Round', value: 'round' },
        { label: 'Square', value: 'square' },
      ] },
      { key: 'lineJoin', label: 'Line join', type: 'select', defaultValue: 'miter', options: [
        { label: 'Miter', value: 'miter' },
        { label: 'Round', value: 'round' },
        { label: 'Bevel', value: 'bevel' },
      ] },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 1, min: 0, max: 1, step: 0.05 },
    ],
  },
  rectangle: {
    toolType: 'rectangle',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Rectangle' },
    ],
    style: [
      { key: 'fill', label: 'Fill color', type: 'color', defaultValue: '#ffffff' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#d1d5db' },
      { key: 'borderWidth', label: 'Border width', type: 'number', defaultValue: 1, min: 0, max: 12, step: 1 },
      { key: 'borderStyle', label: 'Border style', type: 'select', defaultValue: 'solid', options: [
        { label: 'Solid', value: 'solid' },
        { label: 'Dashed', value: 'dashed' },
        { label: 'Dotted', value: 'dotted' },
      ] },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 8, min: 0, max: 48, step: 1 },
      { key: 'opacity', label: 'Opacity', type: 'number', defaultValue: 1, min: 0, max: 1, step: 0.05 },
      { key: 'shadow', label: 'Shadow', type: 'text', defaultValue: '' },
    ],
  },
  date: {
    toolType: 'date',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Date' },
      { key: 'dateSource', label: 'Date source', type: 'select', defaultValue: 'generatedAt', options: [
        { label: 'Generated at', value: 'generatedAt' },
        { label: 'Report start', value: 'reportStart' },
        { label: 'Report end', value: 'reportEnd' },
        { label: 'Custom date', value: 'customDate' },
      ] },
      { key: 'customDate', label: 'Custom date', type: 'date', visibleWhen: { dateSource: 'customDate' } },
      { key: 'format', label: 'Format', type: 'select', defaultValue: 'DD/MM/YYYY HH:mm', options: [
        { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' },
        { label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
        { label: 'DD/MM/YYYY HH:mm', value: 'DD/MM/YYYY HH:mm' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'customFormat', label: 'Custom format', type: 'text', visibleWhen: { format: 'custom' } },
      { key: 'prefix', label: 'Prefix', type: 'text' },
      { key: 'suffix', label: 'text', type: 'text' },
      { key: 'locale', label: 'Locale', type: 'text', defaultValue: 'en-US' },
      { key: 'timezone', label: 'Timezone', type: 'text', defaultValue: 'local' },
    ],
    style: [
      { key: 'fontFamily', label: 'Font family', type: 'text', defaultValue: 'Inter' },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 14, min: 8, max: 72, step: 1 },
      { key: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
      { key: 'align', label: 'Align', type: 'select', defaultValue: 'left', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ] },
    ],
  },
  page_number: {
    toolType: 'page_number',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Page number' },
      { key: 'pattern', label: 'Pattern', type: 'text', defaultValue: 'Page {{page}} / {{totalPages}}' },
      { key: 'showTotalPages', label: 'Show total pages', type: 'boolean', defaultValue: true },
      { key: 'startNumber', label: 'Start number', type: 'number', defaultValue: 1, min: 1, max: 1000, step: 1 },
    ],
    style: [
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 12, min: 8, max: 72, step: 1 },
      { key: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
      { key: 'align', label: 'Align', type: 'select', defaultValue: 'right', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ] },
    ],
  },
  signature: {
    toolType: 'signature',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Signature' },
      { key: 'label', label: 'Label', type: 'text', defaultValue: 'Prepared by' },
      { key: 'signerName', label: 'Signer name', type: 'text' },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'showDateLine', label: 'Show date line', type: 'boolean', defaultValue: true },
    ],
    style: [
      { key: 'lineColor', label: 'Line color', type: 'color', defaultValue: '#111827' },
      { key: 'lineWidth', label: 'Line width', type: 'number', defaultValue: 1, min: 0, max: 12, step: 1 },
      { key: 'lineStyle', label: 'Line style', type: 'select', defaultValue: 'solid', options: [
        { label: 'Solid', value: 'solid' },
        { label: 'Dashed', value: 'dashed' },
        { label: 'Dotted', value: 'dotted' },
      ] },
      { key: 'fontSize', label: 'Font size', type: 'number', defaultValue: 12, min: 8, max: 72, step: 1 },
      { key: 'color', label: 'Color', type: 'color', defaultValue: '#111827' },
    ],
  },
  qrcode: {
    toolType: 'qrcode',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'QR Code' },
      { key: 'dataSource', label: 'Data source', type: 'select', defaultValue: 'static', options: [
        { label: 'Static text', value: 'static' },
        { label: 'URL', value: 'url' },
        { label: 'Report ID', value: 'reportId' },
        { label: 'File ID', value: 'fileId' },
        { label: 'Custom field', value: 'customField' },
      ] },
      { key: 'value', label: 'Value', type: 'text', defaultValue: '' },
    ],
    style: [
      { key: 'size', label: 'Size', type: 'number', defaultValue: 120, min: 32, max: 500, step: 1 },
      { key: 'errorCorrection', label: 'Error correction', type: 'select', defaultValue: 'M', options: [
        { label: 'L', value: 'L' },
        { label: 'M', value: 'M' },
        { label: 'Q', value: 'Q' },
        { label: 'H', value: 'H' },
      ] },
      { key: 'foreground', label: 'Foreground', type: 'color', defaultValue: '#000000' },
      { key: 'background', label: 'Background', type: 'color', defaultValue: '#ffffff' },
      { key: 'showCaption', label: 'Show caption', type: 'boolean', defaultValue: false },
      { key: 'captionText', label: 'Caption text', type: 'text', visibleWhen: { showCaption: true } },
      { key: 'captionFontSize', label: 'Caption font size', type: 'number', defaultValue: 12, min: 8, max: 28, step: 1 },
    ],
  },
  value: {
    toolType: 'value',
    calculation: [
      { key: 'calculationType', label: 'Calculation type', type: 'select', defaultValue: 'cumulative_delta', options: [
        { label: 'Cumulative Delta (Last - First)', value: 'cumulative_delta' },
        { label: 'Sum Interval Delta', value: 'sum_interval' },
        { label: 'Average', value: 'average' },
        { label: 'Peak (Max)', value: 'peak' },
        { label: 'Instant Last', value: 'instant_last' },
        { label: 'Manual Formula', value: 'manual_formula' },
      ] },
      { key: 'energyRole', label: 'Energy/Register role', type: 'select', defaultValue: '', options: [
        { label: 'Not specified', value: '' },
        { label: 'Import kWh (Active Energy)', value: 'import_kwh' },
        { label: 'Export kWh', value: 'export_kwh' },
        { label: 'Total kWh', value: 'total_kwh' },
        { label: 'Peak Demand kW', value: 'demand_kw' },
        { label: 'Active Power kW', value: 'active_power_kw' },
        { label: 'Voltage V', value: 'voltage_v' },
        { label: 'Current A', value: 'current_a' },
      ] },
      { key: 'ctRatio', label: 'CT Ratio', type: 'number', defaultValue: 1 },
      { key: 'ptRatio', label: 'PT Ratio', type: 'number', defaultValue: 1 },
      { key: 'multiplier', label: 'Multiplier', type: 'number', defaultValue: 1 },
      { key: 'scale', label: 'Scale Factor', type: 'number', defaultValue: 1 },
      { key: 'offset', label: 'Offset Value', type: 'number', defaultValue: 0 },
      { key: 'registerAddress', label: 'Register Address', type: 'text' },
      { key: 'registerName', label: 'Register Name', type: 'text' },
    ],
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Value' },
      { key: 'bindingSource', label: 'Binding source', type: 'select', defaultValue: 'tag', options: [
        { label: 'Tag', value: 'tag' },
        { label: 'History', value: 'history' },
        { label: 'Formula', value: 'formula' },
      ] },
      { key: 'project', label: 'Project', type: 'text' },
      { key: 'device', label: 'device', type: 'devicePicker' },
      { key: 'meter', label: 'Meter', type: 'meterPicker' },
      { key: 'tag', label: 'Tag', type: 'tagPicker' },
      { key: 'metric', label: 'Metric', type: 'select', defaultValue: 'live', options: [
        { label: 'Live', value: 'live' },
        { label: 'First', value: 'first' },
        { label: 'Last', value: 'last' },
        { label: 'Usage', value: 'usage' },
        { label: 'Avg', value: 'avg' },
        { label: 'Min', value: 'min' },
        { label: 'Max', value: 'max' },
        { label: 'Peak', value: 'peak' },
      ] },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'today', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This week', value: 'thisWeek' },
        { label: 'Last week', value: 'lastWeek' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'customStart', label: 'Custom start', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'customEnd', label: 'Custom end', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
      { key: 'prefix', label: 'Prefix', type: 'text' },
      { key: 'suffix', label: 'Suffix', type: 'text' },
      { key: 'numberFormat', label: 'Number format', type: 'select', defaultValue: 'raw', options: [
        { label: 'Raw', value: 'raw' },
        { label: 'Comma', value: 'comma' },
        { label: 'Compact', value: 'compact' },
      ] },
      { key: 'fallbackValue', label: 'Fallback value', type: 'text', defaultValue: '--' },
      { key: 'showTimestamp', label: 'Show timestamp', type: 'boolean', defaultValue: false },
      { key: 'showQuality', label: 'Show quality', type: 'boolean', defaultValue: false },
      { key: 'valueColor', label: 'Value color', type: 'color', defaultValue: '#111827' },
      { key: 'unitColor', label: 'Unit color', type: 'color', defaultValue: '#6b7280' },
    ],
    behavior: [
      { key: 'hideWhenZero', label: 'Hide when value is zero', type: 'boolean', defaultValue: false },
      { key: 'showOnlyWhenDataExists', label: 'Show only when data exists', type: 'boolean', defaultValue: false },
    ],
  },
  kpicard: {
    toolType: 'kpicard',
    calculation: [
      { key: 'calculationType', label: 'Calculation type', type: 'select', defaultValue: 'cumulative_delta', options: [
        { label: 'Cumulative Delta (Last - First)', value: 'cumulative_delta' },
        { label: 'Sum Interval Delta', value: 'sum_interval' },
        { label: 'Average', value: 'average' },
        { label: 'Peak (Max)', value: 'peak' },
        { label: 'Instant Last', value: 'instant_last' },
        { label: 'Manual Formula', value: 'manual_formula' },
      ] },
      { key: 'energyRole', label: 'Energy/Register role', type: 'select', defaultValue: '', options: [
        { label: 'Not specified', value: '' },
        { label: 'Import kWh (Active Energy)', value: 'import_kwh' },
        { label: 'Export kWh', value: 'export_kwh' },
        { label: 'Total kWh', value: 'total_kwh' },
        { label: 'Peak Demand kW', value: 'demand_kw' },
        { label: 'Active Power kW', value: 'active_power_kw' },
        { label: 'Voltage V', value: 'voltage_v' },
        { label: 'Current A', value: 'current_a' },
      ] },
      { key: 'ctRatio', label: 'CT Ratio', type: 'number', defaultValue: 1 },
      { key: 'ptRatio', label: 'PT Ratio', type: 'number', defaultValue: 1 },
      { key: 'multiplier', label: 'Multiplier', type: 'number', defaultValue: 1 },
      { key: 'scale', label: 'Scale Factor', type: 'number', defaultValue: 1 },
      { key: 'offset', label: 'Offset Value', type: 'number', defaultValue: 0 },
      { key: 'registerAddress', label: 'Register Address', type: 'text' },
      { key: 'registerName', label: 'Register Name', type: 'text' },
    ],
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'KPI' },
      { key: 'title', label: 'Title', type: 'text', defaultValue: 'KPI' },
      { key: 'subtitle', label: 'Subtitle', type: 'text', defaultValue: '' },
      { key: 'bindingSource', label: 'Binding source', type: 'select', defaultValue: 'tag', options: [
        { label: 'Tag', value: 'tag' },
        { label: 'History', value: 'history' },
        { label: 'Formula', value: 'formula' },
      ] },
      { key: 'metric', label: 'Metric', type: 'select', defaultValue: 'usage', options: [
        { label: 'Live', value: 'live' },
        { label: 'First', value: 'first' },
        { label: 'Last', value: 'last' },
        { label: 'Usage', value: 'usage' },
        { label: 'Avg', value: 'avg' },
        { label: 'Min', value: 'min' },
        { label: 'Max', value: 'max' },
        { label: 'Peak', value: 'peak' },
      ] },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'thisMonth', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This week', value: 'thisWeek' },
        { label: 'Last week', value: 'lastWeek' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
      { key: 'icon', label: 'Icon', type: 'text' },
      { key: 'iconPosition', label: 'Icon position', type: 'select', defaultValue: 'left', options: [
        { label: 'Left', value: 'left' },
        { label: 'Top', value: 'top' },
      ] },
      { key: 'compareMode', label: 'Compare mode', type: 'select', defaultValue: 'none', options: [
        { label: 'None', value: 'none' },
        { label: 'Previous period', value: 'previous' },
        { label: 'Target value', value: 'target' },
      ] },
      { key: 'targetValue', label: 'Target value', type: 'number', defaultValue: 0 },
      { key: 'trendIndicator', label: 'Trend indicator', type: 'boolean', defaultValue: true },
      { key: 'statusColorMode', label: 'Status color mode', type: 'select', defaultValue: 'none', options: [
        { label: 'None', value: 'none' },
        { label: 'Value-based', value: 'value' },
      ] },
    ],
    style: [
      { key: 'background', label: 'Background', type: 'color', defaultValue: '#ffffff' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#d1d5db' },
      { key: 'borderWidth', label: 'Border width', type: 'number', defaultValue: 1, min: 0, max: 12, step: 1 },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 8, min: 0, max: 48, step: 1 },
    ],
  },
  formula: {
    toolType: 'formula',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Formula' },
      { key: 'formula', label: 'Formula', type: 'formulaEditor', defaultValue: 'A + B' },
      { key: 'variableA', label: 'Variable A', type: 'tagPicker' },
      { key: 'variableB', label: 'Variable B', type: 'tagPicker' },
      { key: 'variableC', label: 'Variable C', type: 'tagPicker' },
      { key: 'variableD', label: 'Variable D', type: 'tagPicker' },
      { key: 'variableSource', label: 'Variable source', type: 'select', defaultValue: 'tag', options: [
        { label: 'Tag', value: 'tag' },
        { label: 'Static', value: 'static' },
        { label: 'Billing', value: 'billing' },
        { label: 'Carbon', value: 'carbon' },
      ] },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'today', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This week', value: 'thisWeek' },
        { label: 'Last week', value: 'lastWeek' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
      { key: 'numberFormat', label: 'Number format', type: 'select', defaultValue: 'raw', options: [
        { label: 'Raw', value: 'raw' },
        { label: 'Comma', value: 'comma' },
        { label: 'Compact', value: 'compact' },
      ] },
      { key: 'showFormulaLabel', label: 'Show formula label', type: 'boolean', defaultValue: false },
      { key: 'fallbackValue', label: 'Fallback value', type: 'text', defaultValue: '--' },
    ],
    behavior: [
      { key: 'errorMode', label: 'Error display mode', type: 'select', defaultValue: 'show error', options: [
        { label: 'Show error', value: 'show error' },
        { label: 'Hide', value: 'hide' },
      ] },
    ],
  },
  trend: {
    toolType: 'trend',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Trend' },
      { key: 'tagIds', label: 'Tags', type: 'multiTagPicker' },
      { key: 'period', label: 'Period', type: 'select', defaultValue: '24h', options: [
        { label: '1 hour', value: '1h' },
        { label: '6 hours', value: '6h' },
        { label: '24 hours', value: '24h' },
        { label: '7 days', value: '7d' },
        { label: '30 days', value: '30d' },
      ] },
      { key: 'customStart', label: 'Custom start', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'customEnd', label: 'Custom end', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'aggregation', label: 'Aggregation', type: 'select', defaultValue: 'avg', options: [
        { label: 'Raw', value: 'raw' },
        { label: 'Avg', value: 'avg' },
        { label: 'Min', value: 'min' },
        { label: 'Max', value: 'max' },
        { label: 'Sum', value: 'sum' },
        { label: 'Last', value: 'last' },
      ] },
      { key: 'interval', label: 'Interval', type: 'select', defaultValue: '15m', options: [
        { label: '1 minute', value: '1m' },
        { label: '5 minutes', value: '5m' },
        { label: '15 minutes', value: '15m' },
        { label: '30 minutes', value: '30m' },
        { label: '1 hour', value: '1h' },
        { label: '1 day', value: '1d' },
      ] },
      { key: 'chartStyle', label: 'Chart style', type: 'select', defaultValue: 'line', options: [
        { label: 'Line', value: 'line' },
        { label: 'Area', value: 'area' },
      ] },
      { key: 'showLegend', label: 'Show legend', type: 'boolean', defaultValue: true },
      { key: 'showGrid', label: 'Show grid', type: 'boolean', defaultValue: true },
      { key: 'showTooltip', label: 'Show tooltip', type: 'boolean', defaultValue: true },
      { key: 'showPoints', label: 'Show points', type: 'boolean', defaultValue: false },
      { key: 'smoothLine', label: 'Smooth line', type: 'boolean', defaultValue: false },
      { key: 'yAxisAuto', label: 'Y axis auto', type: 'boolean', defaultValue: true },
      { key: 'yAxisMin', label: 'Y axis min', type: 'number', defaultValue: 0, visibleWhen: { yAxisAuto: false } },
      { key: 'yAxisMax', label: 'Y axis max', type: 'number', defaultValue: 100, visibleWhen: { yAxisAuto: false } },
      { key: 'yAxisUnit', label: 'Y axis unit', type: 'text' },
      { key: 'thresholdLine', label: 'Threshold line', type: 'boolean', defaultValue: false },
      { key: 'thresholdValue', label: 'Threshold value', type: 'number', defaultValue: 0, visibleWhen: { thresholdLine: true } },
      { key: 'emptyDataMode', label: 'Empty data mode', type: 'select', defaultValue: 'show blank', options: [
        { label: 'Show blank', value: 'show blank' },
        { label: 'Show no data', value: 'show no data' },
        { label: 'Hide object', value: 'hide object' },
      ] },
    ],
  },
  echart: {
    toolType: 'echart',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Chart' },
      { key: 'chartType', label: 'Chart type', type: 'select', defaultValue: 'bar', options: [
        { label: 'Line', value: 'line' },
        { label: 'Bar', value: 'bar' },
        { label: 'Pie', value: 'pie' },
        { label: 'Area', value: 'area' },
      ] },
      { key: 'dataSource', label: 'Data source', type: 'select', defaultValue: 'tags', options: [
        { label: 'Tags', value: 'tags' },
        { label: 'Billing', value: 'billing' },
        { label: 'Alarm', value: 'alarm' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'tagIds', label: 'Tags', type: 'multiTagPicker' },
      { key: 'groupBy', label: 'Group by', type: 'select', defaultValue: 'time', options: [
        { label: 'Device', value: 'device' },
        { label: 'Meter', value: 'meter' },
        { label: 'Time', value: 'time' },
        { label: 'Category', value: 'category' },
      ] },
      { key: 'aggregation', label: 'Aggregation', type: 'select', defaultValue: 'sum', options: [
        { label: 'Sum', value: 'sum' },
        { label: 'Avg', value: 'avg' },
        { label: 'Min', value: 'min' },
        { label: 'Max', value: 'max' },
        { label: 'Count', value: 'count' },
      ] },
      { key: 'period', label: 'Period', type: 'select', defaultValue: '7d', options: [
        { label: '1 hour', value: '1h' },
        { label: '6 hours', value: '6h' },
        { label: '24 hours', value: '24h' },
        { label: '7 days', value: '7d' },
        { label: '30 days', value: '30d' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'customStart', label: 'Custom start', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'customEnd', label: 'Custom end', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'legend', label: 'Show legend', type: 'boolean', defaultValue: true },
      { key: 'label', label: 'Show labels', type: 'boolean', defaultValue: false },
      { key: 'tooltip', label: 'Show tooltip', type: 'boolean', defaultValue: true },
      { key: 'axisTitle', label: 'Axis title', type: 'text' },
      { key: 'yAxisUnit', label: 'Y axis unit', type: 'text' },
      { key: 'colorMode', label: 'Color mode', type: 'select', defaultValue: 'auto', options: [
        { label: 'Auto', value: 'auto' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'pieLabelMode', label: 'Pie label mode', type: 'select', defaultValue: 'outside', options: [
        { label: 'Outside', value: 'outside' },
        { label: 'Inside', value: 'inside' },
        { label: 'Center', value: 'center' },
      ], visibleWhen: { chartType: 'pie' } },
      { key: 'barOrientation', label: 'Bar orientation', type: 'select', defaultValue: 'vertical', options: [
        { label: 'Vertical', value: 'vertical' },
        { label: 'Horizontal', value: 'horizontal' },
      ], visibleWhen: { chartType: 'bar' } },
    ],
  },
  tagtable: {
    toolType: 'tagtable',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Tag Table' },
      { key: 'dataSource', label: 'Data source', type: 'select', defaultValue: 'current', options: [
        { label: 'Current values', value: 'current' },
        { label: 'Historical summary', value: 'history' },
      ] },
      { key: 'project', label: 'Project', type: 'text' },
      { key: 'deviceScope', label: 'Device scope', type: 'devicePicker' },
      { key: 'meterScope', label: 'Meter scope', type: 'meterPicker' },
      { key: 'selectedTags', label: 'Selected tags', type: 'multiTagPicker' },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'today', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This week', value: 'thisWeek' },
        { label: 'Last week', value: 'lastWeek' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'customStart', label: 'Custom start', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'customEnd', label: 'Custom end', type: 'date', visibleWhen: { period: 'custom' } },
    ],
    table: [
      { key: 'columns', label: 'Columns', type: 'columnBuilder', defaultValue: ['tagName','value','unit','timestamp','quality'] },
      { key: 'columnOrder', label: 'Column order', type: 'text' },
      { key: 'columnWidth', label: 'Column width', type: 'text' },
      { key: 'rowHeight', label: 'row height', type: 'number', defaultValue: 28, min: 16, max: 72, step: 1 },
      { key: 'headerStyle', label: 'Header style', type: 'text' },
      { key: 'bodyStyle', label: 'Body style', type: 'text' },
      { key: 'alternateRowColor', label: 'Alternate row color', type: 'boolean', defaultValue: false },
      { key: 'sorting', label: 'Sorting', type: 'text' },
      { key: 'maxRows', label: 'Max rows', type: 'number', defaultValue: 50, min: 1, max: 200, step: 1 },
      { key: 'pageBreak', label: 'Page break', type: 'boolean', defaultValue: false },
      { key: 'repeatHeader', label: 'Repeat header', type: 'boolean', defaultValue: true },
      { key: 'emptyTableMessage', label: 'Empty table message', type: 'text', defaultValue: 'No data' },
    ],
  },
  alarmtable: {
    toolType: 'alarmtable',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Alarm Table' },
      { key: 'mode', label: 'Mode', type: 'select', defaultValue: 'history', options: [
        { label: 'Active', value: 'active' },
        { label: 'History', value: 'history' },
      ] },
      { key: 'project', label: 'Project', type: 'text' },
      { key: 'deviceScope', label: 'Device scope', type: 'devicePicker' },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'lastWeek', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This week', value: 'thisWeek' },
        { label: 'Last week', value: 'lastWeek' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
      ] },
      { key: 'levelFilter', label: 'Level filter', type: 'select', defaultValue: 'all', options: [
        { label: 'All', value: 'all' },
        { label: 'Info', value: 'info' },
        { label: 'Warning', value: 'warning' },
        { label: 'Critical', value: 'critical' },
      ] },
      { key: 'statusFilter', label: 'Status filter', type: 'text' },
      { key: 'maxRows', label: 'Max rows', type: 'number', defaultValue: 100, min: 1, max: 500, step: 1 },
    ],
    table: [
      { key: 'columns', label: 'Columns', type: 'columnBuilder', defaultValue: ['time','device','tag','level','message','value','status','acknowledged'] },
      { key: 'sortBy', label: 'Sort by', type: 'text' },
      { key: 'sortDirection', label: 'Sort direction', type: 'select', defaultValue: 'desc', options: [{ label: 'Desc', value: 'desc' }, { label: 'Asc', value: 'asc' }] },
      { key: 'rowColorByLevel', label: 'Row color by level', type: 'boolean', defaultValue: true },
      { key: 'repeatHeader', label: 'Repeat header', type: 'boolean', defaultValue: true },
      { key: 'pageBreak', label: 'Page break', type: 'boolean', defaultValue: false },
      { key: 'emptyTableMessage', label: 'Empty table message', type: 'text', defaultValue: 'No alarms' },
    ],
  },
  meter_billing_table: {
    toolType: 'meter_billing_table',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Meter Billing Table' },
      { key: 'project', label: 'Project', type: 'text' },
      { key: 'deviceScope', label: 'Device scope', type: 'devicePicker' },
      { key: 'meterScope', label: 'Meter scope', type: 'meterPicker' },
      { key: 'energyTag', label: 'Energy tag', type: 'tagPicker' },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'month', options: [
        { label: 'Today', value: 'today' },
        { label: 'This month', value: 'month' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'customStart', label: 'Custom start', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'customEnd', label: 'Custom end', type: 'date', visibleWhen: { period: 'custom' } },
      { key: 'tariff', label: 'Tariff', type: 'text' },
      { key: 'rateMode', label: 'Rate mode', type: 'select', defaultValue: 'flat', options: [
        { label: 'Flat', value: 'flat' },
        { label: 'TOU', value: 'tou' },
        { label: 'TOD', value: 'tod' },
      ] },
      { key: 'flatRate', label: 'Flat rate', type: 'number', defaultValue: 0 },
      { key: 'multiplier', label: 'Multiplier', type: 'number', defaultValue: 1 },
      { key: 'ctRatio', label: 'CT ratio', type: 'number', defaultValue: 1 },
      { key: 'serviceCharge', label: 'Service charge', type: 'number', defaultValue: 0 },
      { key: 'vatPercent', label: 'VAT percent', type: 'number', defaultValue: 7 },
      { key: 'currency', label: 'Currency', type: 'text', defaultValue: 'THB' },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
    ],
    table: [
      { key: 'columns', label: 'Columns', type: 'columnBuilder', defaultValue: ['no','meterName','deviceName','tagName','firstReading','lastReading','usage','ctRatio','multiplier','rate','amount','serviceCharge','vat','total','remark'] },
      { key: 'columnOrder', label: 'Column order', type: 'text' },
      { key: 'columnWidth', label: 'Column width', type: 'text' },
      { key: 'summaryRow', label: 'Summary row', type: 'boolean', defaultValue: true },
      { key: 'repeatHeader', label: 'Repeat header', type: 'boolean', defaultValue: true },
      { key: 'alternateRowColor', label: 'Alternate row color', type: 'boolean', defaultValue: false },
      { key: 'pageBreak', label: 'Page break', type: 'boolean', defaultValue: false },
    ],
  },
  energy_summary: {
    toolType: 'energy_summary',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Energy Summary' },
      { key: 'scope', label: 'Scope', type: 'select', defaultValue: 'project', options: [
        { label: 'Project', value: 'project' },
        { label: 'Device', value: 'device' },
        { label: 'Meter', value: 'meter' },
      ] },
      { key: 'energyTag', label: 'Energy tag', type: 'tagPicker' },
      { key: 'demandTag', label: 'Demand tag', type: 'tagPicker' },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'thisMonth', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'layout', label: 'Layout', type: 'select', defaultValue: 'card', options: [
        { label: 'Card', value: 'card' },
        { label: 'Table', value: 'table' },
        { label: 'Compact', value: 'compact' },
      ] },
      { key: 'showComparison', label: 'Show comparison', type: 'boolean', defaultValue: false },
      { key: 'comparePreviousPeriod', label: 'Compare previous period', type: 'boolean', defaultValue: false },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
    ],
  },
  cost_summary: {
    toolType: 'cost_summary',
    general: [
      { key: 'name', label: 'Name', type: 'text', defaultValue: 'Cost Summary' },
      { key: 'billingSource', label: 'Billing source', type: 'select', defaultValue: 'billing', options: [
        { label: 'Billing', value: 'billing' },
        { label: 'Meter', value: 'meter' },
      ] },
      { key: 'period', label: 'Period', type: 'select', defaultValue: 'thisMonth', options: [
        { label: 'Today', value: 'today' },
        { label: 'Yesterday', value: 'yesterday' },
        { label: 'This month', value: 'thisMonth' },
        { label: 'Last month', value: 'lastMonth' },
        { label: 'Custom', value: 'custom' },
      ] },
      { key: 'tariff', label: 'Tariff', type: 'text' },
      { key: 'rate', label: 'Rate', type: 'number', defaultValue: 0 },
      { key: 'serviceCharge', label: 'Service charge', type: 'number', defaultValue: 0 },
      { key: 'vatPercent', label: 'VAT percent', type: 'number', defaultValue: 7 },
      { key: 'currency', label: 'Currency', type: 'text', defaultValue: 'THB' },
      { key: 'showSubtotal', label: 'Show subtotal', type: 'boolean', defaultValue: true },
      { key: 'showServiceCharge', label: 'Show service charge', type: 'boolean', defaultValue: true },
      { key: 'showVat', label: 'Show VAT', type: 'boolean', defaultValue: true },
      { key: 'showGrandTotal', label: 'Show grand total', type: 'boolean', defaultValue: true },
      { key: 'decimal', label: 'Decimal', type: 'number', defaultValue: 2, min: 0, max: 6, step: 1 },
    ],
  },
};
